services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    network_mode: "host"
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    command: npm start

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    network_mode: "host"
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    command: npm run dev